/// Flutter icons BankAppIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BankAppIcons
///      fonts:
///       - asset: fonts/BankAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BankAppIcons {
  BankAppIcons._();

  static const _kFontFam = 'BankAppIcons';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usd_sign = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eur_sign = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData metal_sign = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
